### PR TITLE
Follow latest convention and prepare Proptype for TabOption

### PR DESCRIPTION
**Pull request by muhaimincs**

### CODE REVIEW

**Comment by kirankalyan5** [comment]
@muhaimincs Great work, this is something which I had planned to introduce. So It's very clean to write test. 

I had also planned to introduce `flow` and remove `propTypes` would you like to introduce as a part of this PR? 

If you do not have time then I can take it. :)

Thanks again! Much Appreciated 🍻

**Comment by kirankalyan5** [comment]
Hi, @muhaimincs I have merged the PR, with some very minor changes. You could have a look at it.

Thanks again for the PR.

**Comment by muhaimincs** [comment]
Thanks for the merge. By the way it's totally up to you as to improve for the benefits of others. Great solution to bring iOS experience  to react-native

**Comment by kirankalyan5** [comment]
Thanks, @muhaimincs ! Please feel free to raise PRs :)

**Pull request merged**
