### PR TITLE
Disable removeClippedSubviews

### PR DESCRIPTION
**Pull request by alexdunae**
Fixes blank initial view reported in issue #15 - tested on iOS

### CODE REVIEW

**Comment by brunolemos** [comment]
@kirankalyan5 I can confirm this fixes the issue, please merge it

**Comment by Paul-Todd** [comment]
Please merge this as well - fixes the issue for me too.

**Comment by adeelraza** [comment]
+1

**Comment by kirankalyan5** [comment]
merge commit - Disable removeClippedSubviews

**Comment by brunolemos** [comment]
Thanks! Let us know after npm publish

**Comment by kirankalyan5** [comment]
image

@brunolemos - Published 👍

**Comment by alexdunae** [comment]
😍

**Pull request merged**
