### PR TITLE
Adding support for react-native-web

### PR DESCRIPTION
**Pull request by KjellConnelly**
This component works for React-Native-Web until you webpack publish, then things go haywire. Created a new es6 version of the component that is only slightly different (instead of View.propTypes and Text.propTypes, I used ViewPropTypes (which is imported from react-native)). Then I created an ES5 version of the same file using babel. 

Finally, the package.json file has 'main' changed so that instead of loading SegmentControlTab.js, it just loads SegmentControlTab (react native already knows how to handle adding the .js to the end, and with webpack, you can make it try to load .web.js files before .js files. So it'll load the ES5 version.

### CODE REVIEW

**Comment by kirankalyan5** [comment]
@KjellConnelly can you add an example for this?

**Comment by KjellConnelly** [comment]
What do you mean an example? Like a screenshot or the component working in the browser?

**Comment by kirankalyan5** [comment]
I would mean a working example in the browser and we could take a screen shot of the same to update in the readme.

**Comment by KjellConnelly** [comment]
Just updated my fork. I haven't ever made changes after I had already made a pull request, so if you don't see the changes on your side, let me know...

I added a screenshot of it running on Chrome and a link to the example running in the browser.

**Comment by kirankalyan5** [comment]
Awesome @KjellConnelly, I will have a look and merge it soon.
Thanks!

**Comment by SrinivasanTarget** [comment]
@kirankalyan5 Its been a year... any plans to look?

**Comment by kirankalyan5** [comment]
@KjellConnelly thanks again for this  PR.Sorry for the delay!
No plans for getting this feature in the near future as it should be completely tested.

Closing this for now.

**Comment by KjellConnelly** [comment]
I’m not sure if this’ll fix the issue, but I think you can change your webpack config to compile this package specifically instead of ignoring it like it typically ignores all node_modules packages. Don’t know the code for it, but shouldn’t be difficult.

**Comment by kirankalyan5** [comment]
I agree, the PR is a bit old and there are quite a few changes made to the source since then. I would prefer the web source files should be in sync with native one.

Also, I'm planning to add a test to segmentedControlTab, so the code is tested. 

I was planning to introduce this after the implementing the must-have TODO's.
1:  jest test.
2:  Flow support.
3. CI which runs on eslint, flow, and jest.

if you would like to contribute help appreciated.

**Pull request closed without merging**
