### PR TITLE
Added support for badges

### PR DESCRIPTION
**Pull request by asessa**
badges

### CODE REVIEW

**Comment by asessa** [comment]
fixed also glitch on iOS

**Comment by kirankalyan5** [comment]
Hi @asessa thanks for the PR and sorry for the delay. The feature looks interesting. But the files have conflicts, it would be great if you can resolve them :)

Thanks

**Comment by asessa** [comment]
@kirankalyan5  done,

I can update the docs when merged.

props:

badges - array where you specify the badge number value per index.
tabBadgeContainerStyle - overrides the default badge style.
activeTabBadgeContainerStyle - overrides the default active badge style.

**Comment by kirankalyan5** [comment]
Hi @asessa I have merged the PR. Looks nice :) 
It would be great if you can update the example and the readme with a screenshot.

Thanks.

**Pull request merged**
