### PR TITLE
add support for testIDs

### PR DESCRIPTION
**Pull request by maruan-alush-ibm**
Adding support for testID prop to be passed as it is widely used in E2E testing for in mobile apps.

### CODE REVIEW

**Review by kirankalyan5 — APPROVED** [review]
Thanks for the PR, LGTM 👍

**Comment by maruan-alush-ibm** [comment]
Thanks a lot for approving so quickly! How long does it usually take for the changes to be pushed to the npm package?

**Comment by kirankalyan5** [comment]
@maruan-alush-ibm - I am a bit occupied, Maybe in a couple of days/weeks. In between, I would wait for some incoming changes. So it could be shipped along with the new version.
Thanks

**Comment by maruan-alush-ibm** [comment]
@kirankalyan5 I totally appreciate you're busy! Would you be able to, however, give any date/time frame which is a bit more specific? Just want to be sure as we also have deadlines and I want to see if we need to locally patch this or can afford to wait for the new version to be pushed to npm. Once again thank you for your amazing library!

**Pull request merged**
