### PR TITLE
Allow for custom first and last tab.

### PR DESCRIPTION
**Pull request by jacobhummel**
First off, great library!

I am using multiple instances of this in my app. In one instance I am really overriding the style and creating space between the tabs. This default first and last tab style prevents me from achieving the look I'm going for. I added optional firstTabStyle and lastTabStyle.

Before:
screen shot 2017-08-28 at 9 44 17 pm

After:
screen shot 2017-08-28 at 10 08 32 pm

### CODE REVIEW

**Comment by kirankalyan5** [comment]
@jacobhummel Thanks for the PR and sorry for the delay in reply. I will test once and merge the PR.
Thanks

**Comment by kirankalyan5** [comment]
@jacobhummel this branch has conflicts, can you have a check. Thanks

**Comment by derekbrown** [comment]
@kirankalyan5 @jacobhummel Are the conflicts here being resolved soon? If not, I can take over and submit a new PR soon.

**Comment by kirankalyan5** [comment]
@derekbrown Sound good! You can submit a new PR.

Thanks in advance,

**Pull request closed without merging**
